// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc.api;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.api.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string passwd = 2;</code>
   * @return The passwd.
   */
  java.lang.String getPasswd();
  /**
   * <code>string passwd = 2;</code>
   * @return The bytes for passwd.
   */
  com.google.protobuf.ByteString
      getPasswdBytes();
}
