// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc.api;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_api_LoginRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_api_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_api_APIResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_api_APIResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_api_Empty_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_api_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\024com.example.grpc.api\"0\n\014Lo" +
      "ginRequest\022\020\n\010username\030\001 \001(\t\022\016\n\006passwd\030\002" +
      " \001(\t\"<\n\013APIResponse\022\027\n\017responsemessage\030\001" +
      " \001(\t\022\024\n\014responseCode\030\002 \001(\005\"\007\n\005Empty2\240\001\n\004" +
      "user\022N\n\005login\022\".com.example.grpc.api.Log" +
      "inRequest\032!.com.example.grpc.api.APIResp" +
      "onse\022H\n\006logout\022\033.com.example.grpc.api.Em" +
      "pty\032!.com.example.grpc.api.APIResponseB+" +
      "\n\024com.example.grpc.apiB\021RPCDateServiceAp" +
      "iP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpc_api_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_api_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_api_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Passwd", });
    internal_static_com_example_grpc_api_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_api_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_api_APIResponse_descriptor,
        new java.lang.String[] { "Responsemessage", "ResponseCode", });
    internal_static_com_example_grpc_api_Empty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_api_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_api_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
