// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc.api;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.api.APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responsemessage = 1;</code>
   * @return The responsemessage.
   */
  java.lang.String getResponsemessage();
  /**
   * <code>string responsemessage = 1;</code>
   * @return The bytes for responsemessage.
   */
  com.google.protobuf.ByteString
      getResponsemessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   * @return The responseCode.
   */
  int getResponseCode();
}
