// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.grpc.api;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.api.Empty)
    com.google.protobuf.MessageOrBuilder {
}
